services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    restart: always

  api_endpoint:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: business_data_api
    ports:
      - "8078:8000"
    env_file:
      - .env
    depends_on:
      - redis

  worker-krsapi:
    build:
      context: .
      dockerfile: Dockerfile.api
    command: ["poetry", "run", "python", "run_worker.py", "KRSAPI"]
    container_name: business_data_worker_krsapi
    env_file:
      - .env
    depends_on:
      - redis
      - api_endpoint
  
  worker-krsdf:
    build:
      context: .
      dockerfile: Dockerfile.api
    command: ["poetry", "run", "python", "run_worker.py", "KRSDF"]
    container_name: business_data_worker_krsdf
    env_file:
      - .env
    depends_on:
      - redis
      - api_endpoint

  spark-etl:
    build:
      context: .
      dockerfile: Dockerfile.spark
    container_name: business_data_spark
    env_file:
      - .env
